-- mdOnline H2 数据库建表脚本（开发环境）
-- H2 兼容 PostgreSQL 模式

CREATE TABLE IF NOT EXISTS article (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)  NOT NULL DEFAULT '',
    content     TEXT          NOT NULL DEFAULT '',
    summary     VARCHAR(500)  DEFAULT '',
    word_count  INT           DEFAULT 0,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    deleted     BOOLEAN       DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    parent_id   BIGINT        DEFAULT 0,
    sort_order  INT           DEFAULT 0,
    created_at  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    deleted     BOOLEAN       DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS article_category (
    article_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, category_id)
);
